[package]
name = "pred"
version = "0.1.0"
authors = ["Romain Ruetschi <romain@informal.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "0.1.9"
derive_more = "0.99.5"
colored = "1.9.3"

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
