[package]
name = "pred"
version = "0.1.0"
authors = ["Romain Ruetschi <romain@informal.systems>"]
edition = "2018"

[features]
default = ["inspect"]
inspect = ["colored"]
no-color = ["colored/no-color"]

[dependencies]
cfg-if = "0.1.10"
derive_more = "0.99.5"

# feature: inspect/colors
colored = { version = "1.9.3", optional = true }

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
